### PR TITLE
Change master to main

### PR DESCRIPTION
**Pull request by Racer159**
There is technically a redirect in place for the "Edit this page" button but I am not sure how long that lasts.  This brings the docs pages in line with the master -> main change in Zarf itself.

### CODE REVIEW

**Comment by Racer159** [comment]
Here is the blue bar this gets rid of
image

**Comment by Madeline-UX** [comment]
@Racer159 has this issue been resolved? Or can we close it?

**Review by bdfinst — APPROVED** [review]
LGTM

**Review by bdfinst — APPROVED** [review]
Resolved conflict

**Pull request merged**
